### ISSUE TITLE
Is the dependency to the Rust devcontainer feature needed?

### ISSUE THREAD

**Issue by andreimaxim** [rails/devcontainer#32]
While playing around with the devcontainers in edge Rails, I've noticed that the following extensions were added to my VSCode:
* CodeLLDB
* crates
* Even Better TOML
* rust-analyzer

After a bit of an investigation, I discovered that these extensions are installed by the [Rust feature](https://github.com/devcontainers/features/blob/main/src/rust/devcontainer-feature.json#L46), which has been recently [marked as a dependency for the Ruby feature](https://github.com/rails/devcontainer/pull/29). I could not find any arguments in favor of this approach (the PR mentions an incompatibility with a newer version of Rust), so I figured I could start a conversation on this topic.

I'd argue in favor of replacing the dependency to the Rust feature with installing the `rustc` package from the operating system. There are four reasons:
* It adds unnecessary packages, like cargo, and third-party VS Code extensions that cannot be disabled
* It increases the build time as Rust needs to be compiled
* Following a specific version of Rust will eventually require rebuilding the container quite often, since Rust seems to be releasing a new version every month or so
* It adds little to no benefit for the regular Rails developer and can be confusing for newcomers (to Rails or to devcontainers)

If my arguments are strong enough, I'd be more than happy to create a PR :-)

**Comment by ryanjafari** [comment]
Ah I see, yes that makes sense to me.

Happy to help.

**Comment by andrewn617** [comment]
Hi @andreimaxim thank you for your report.

I think it's not a bad idea to use `rustc` instead of compiling rust outselves (with the feature or otherwise). Originally I did not do it because it would not allow us to use the latest version of rust, but the debian package looks like it is on 1.63 so I think it's ok.

I will work on that. If I do run into any issues, alternatively I will just disable the extensions from the image's dev container.

One thing I want to clarify:

> Following a specific version of Rust will eventually require rebuilding the container quite often, since Rust seems to be releasing a new version every month or so

It is not our intention to lock to a specific Rust version for the long term. There is [an open issue with Rust 1.78](https://github.com/rust-lang/rust/issues/125619) that causes ruby to not build on arm machines, so we locked to 1.77 for now until that issue is fixed. But I will remove that once the fix is released (or just by using rustc) and new versions of rust will not be a reason to release new versions of the image - unless of course they fix some breaking issue with ruby / yjit, in which case we may have to revisit using debian `rustc`.
