### ISSUE TITLE
add support for other version managers

### ISSUE THREAD

**Issue by SethHorsley** [rails/devcontainer#62]
Would be nice to add support for asdf, or mise or even RVM.

A lot of projects require more than one language being able to have one less file the `.ruby-version`.

Rbenv doesn't support the `.tool-versions` or even support the ruby directive from a gemfile which rvm does.

**Comment by rafaelfranca** [comment]
I was trying to avoid that. The way you deal with multiple languages versions in dev container is different from the `.tool-versions`. You use the devcontainer features to make sure they are installed with the right versions. I'm pretty sure there is a mise, or asdf feature for devcontainer. If you want to use that, you can use them.

The Ruby feature from Microsoft allows you to install other version managers, and I was trying to not do the same. We can, but I need a better justification than supporting `.tools-versions` because the right way to manage different languages in devcontainer is to use different features.

**Comment by andrewn617** [comment]
I agree, I don't see a use case for supporting multiple version managers. As Rafael said, a feature using RVM or other versions would make sense if you want this.
